export const RESOURCE_OPERATIONS = [
  {
    id: "resource.templates",
    command: ["resource", "templates"],
    method: "GET",
    path: "/openapi/v2/video/effects/templates/list",
    bodyMode: "none",
    validationPolicy: "resource.templates",
    billing: "read-only",
    asynchronous: false,
    resultIdPath: null,
  },
  {
    id: "resource.tts-speakers",
    command: ["resource", "tts-speakers"],
    method: "GET",
    path: "/openapi/v2/video/tts_speaker",
    bodyMode: "none",
    validationPolicy: "resource.tts-speakers",
    billing: "read-only",
    asynchronous: false,
    resultIdPath: null,
  },
  {
    id: "resource.restyle-effects",
    command: ["resource", "restyle-effects"],
    method: "GET",
    path: "/openapi/v2/video/restyle/list",
    bodyMode: "none",
    validationPolicy: "resource.restyle-effects",
    billing: "read-only",
    asynchronous: false,
    resultIdPath: null,
  },
  {
    id: "voice.create",
    command: ["voice", "create"],
    method: "POST",
    path: "/openapi/v2/video/tts_speaker",
    bodyMode: "json",
    validationPolicy: "voice.create",
    billing: "non-billable",
    asynchronous: false,
    resultIdPath: "Resp.speaker_id",
  },
  {
    id: "voice.delete",
    command: ["voice", "delete"],
    method: "DELETE",
    path: "/openapi/v2/video/tts_speaker/{speaker_id}",
    bodyMode: "none",
    validationPolicy: "voice.delete",
    billing: "non-billable",
    asynchronous: false,
    resultIdPath: null,
  },
  {
    id: "image.template",
    command: ["image", "template"],
    method: "POST",
    path: "/openapi/v2/image/template/generate",
    bodyMode: "json",
    validationPolicy: "image.template",
    billing: "billable",
    asynchronous: true,
    resultIdPath: "Resp.image_id",
  },
  {
    id: "image.status",
    command: ["image", "status"],
    method: "GET",
    path: "/openapi/v2/image/result/{image_id}",
    bodyMode: "none",
    validationPolicy: "image.status",
    billing: "read-only",
    asynchronous: false,
    resultIdPath: "Resp.image_id",
  },
];
